import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet';
import L from 'leaflet';
import { getHeritage, askVirasat } from './lib/api';

const categories = ['All', 'Monuments', 'Architecture', 'Festivals', 'Traditional Arts', 'Crafts', 'Food Heritage', 'Folk Traditions', 'Languages', 'Historical Sites'];
const placeholder = 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80';

function Brand() { return <Link className="brand" to="/"><span className="brand-mark">VS</span><span>Virasat Setu</span></Link>; }
function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="container nav-wrap"><Brand/><button className="mobile-menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Menu'}</button><nav className={open ? 'nav open' : 'nav'}>{[['Explore','/explore'],['Map','/map'],['Virasat AI','/ai'],['Quiz','/quiz'],['About','/about']].map(([label,path]) => <NavLink key={path} to={path} onClick={() => setOpen(false)}>{label}</NavLink>)}<NavLink className="search-link" to="/explore">Search <span>⌕</span></NavLink></nav></div></header>;
}
function Footer() { return <footer><div className="container footer-grid"><div><Brand/><p>A bridge to India's living heritage.</p></div><div><p className="eyebrow">Explore</p><Link to="/explore">Heritage Explorer</Link><Link to="/map">Interactive Map</Link><Link to="/quiz">Heritage Quiz</Link></div><div><p className="eyebrow">Project</p><Link to="/about">About Virasat Setu</Link><span>SIH Student Innovation Project</span></div></div><div className="container footer-bottom"><span>Built for discovery, learning and conversation.</span><span>© 2026 Virasat Setu</span></div></footer>; }
function Layout({ children }) { const location = useLocation(); useEffect(() => window.scrollTo({ top: 0, behavior: 'instant' }), [location.pathname]); return <><Header/><main>{children}</main><Footer/></>; }
function Image({ src, alt, className='' }) { const [failed, setFailed] = useState(false); return failed ? <div className={`image-fallback ${className}`} role="img" aria-label={alt}>Virasat Setu</div> : <img className={className} src={src || placeholder} alt={alt} loading="lazy" onError={() => setFailed(true)}/>; }
function SectionIntro({ eyebrow, title, text, action }) { return <div className="section-intro"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{text && <p>{text}</p>}{action}</div>; }
function HeritageCard({ item, compact=false }) { return <article className={compact ? 'heritage-card compact' : 'heritage-card'}><Link to={`/heritage/${item.id}`}><Image src={item.image} alt={item.name}/><div className="card-body"><div className="meta"><span>{item.category}</span><span>{item.state}</span></div><h3>{item.name}</h3><p>{item.description}</p><span className="text-link">Explore <span>→</span></span></div></Link></article>; }
function Home({ heritage }) {
  const featured = heritage.slice(0, 4);
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">India's cultural heritage</p><h1>Discover the stories that shaped us.</h1><p className="hero-lede">Explore India's monuments, traditions, crafts, festivals and living cultures through one connected digital experience.</p><div className="hero-actions"><Link className="btn primary" to="/explore">Explore Heritage <span>↗</span></Link><Link className="btn text-btn" to="/map">Explore the Map <span>→</span></Link></div></div><div className="hero-visual"><Image src="https://commons.wikimedia.org/wiki/Special:FilePath/Sanchi%20Stupa%20No.1.jpg" alt="Sanchi Stupa"/><div className="hero-caption"><span>Sanchi, Madhya Pradesh</span><span>01 / 09</span></div></div></div></section>
    <section className="statement"><div className="container statement-grid"><p className="eyebrow">The idea</p><div><h2>India's heritage is everywhere. <em>Finding it shouldn't be difficult.</em></h2><p>Virasat Setu brings scattered stories into one approachable place — so a student can move from a question, to a map, to a real cultural context in a few minutes.</p></div></div></section>
    <section className="featured section"><div className="container"><SectionIntro eyebrow="Start exploring" title="A few places to begin" text="A small, carefully chosen MVP dataset — designed to grow with verified sources and community contributions." action={<Link className="arrow-link" to="/explore">View all heritage →</Link>}/><div className="featured-grid">{featured.map((item, i) => <div key={item.id} className={`featured-slot slot-${i}`}><HeritageCard item={item}/></div>)}</div></div></section>
    <section className="map-teaser"><div className="container map-teaser-inner"><div><p className="eyebrow">See heritage differently</p><h2>From a list of places to a living map of India.</h2><p>Trace the locations in the MVP and open each marker to learn what makes the place culturally significant.</p><Link className="btn primary" to="/map">Open interactive map</Link></div><div className="mini-map-art"><div className="india-line">INDIA</div><span className="map-dot d1"/><span className="map-dot d2"/><span className="map-dot d3"/><span className="map-dot d4"/></div></div></section>
    <section className="ai-teaser section"><div className="container ai-panel"><div><p className="eyebrow">Virasat AI · demo</p><h2>Have a question? Start with curiosity.</h2><p>Ask about a place, a craft, a festival or a region. In this MVP, responses come from the project’s local heritage knowledge base.</p><Link className="btn dark" to="/ai">Ask Virasat AI <span>→</span></Link></div><div className="question-stack"><div>“Why is Madhubani painting important?”</div><div>“What can I explore in Madhya Pradesh?”</div><div>“Tell me about Konark.”</div></div></div></section>
  </>;
}
function Filters({ search, setSearch, category, setCategory, state, setState, states }) { return <div className="filters"><label className="search-box"><span>⌕</span><input aria-label="Search heritage" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search places, crafts, states..."/><kbd>⌘ K</kbd></label><select value={category} onChange={e => setCategory(e.target.value)} aria-label="Filter by category">{categories.map(c => <option key={c}>{c}</option>)}</select><select value={state} onChange={e => setState(e.target.value)} aria-label="Filter by state"><option value="All">All states</option>{states.map(s => <option key={s}>{s}</option>)}</select></div>; }
function Explore({ heritage }) {
  const [search,setSearch]=useState(''); const [category,setCategory]=useState('All'); const [state,setState]=useState('All');
  const states = useMemo(() => [...new Set(heritage.map(x=>x.state))].sort(), [heritage]);
  const results = useMemo(() => heritage.filter(x => (category==='All'||x.category===category)&&(state==='All'||x.state===state)&&[x.name,x.state,x.city,x.category,x.description,...x.tags].join(' ').toLowerCase().includes(search.toLowerCase())), [heritage,search,category,state]);
  useEffect(() => { const onKey = e => { if ((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k') { e.preventDefault(); document.querySelector('.search-box input')?.focus(); } }; window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey); },[]);
  return <div className="page"><div className="container page-head"><p className="eyebrow">Heritage explorer</p><h1>Find something worth knowing.</h1><p>Browse a growing collection of places, practices and craft traditions. Search by name, region or category.</p></div><div className="container"><Filters {...{search,setSearch,category,setCategory,state,setState,states}}/><div className="result-line"><span>{results.length} heritage entries</span>{search && <button onClick={()=>setSearch('')}>Clear search ×</button>}</div>{results.length ? <div className="explore-grid">{results.map(item=><HeritageCard key={item.id} item={item}/>)}</div> : <EmptyState title="Nothing matched that search." text="Try a broader place name, state or category." action={<button className="btn secondary" onClick={()=>{setSearch('');setCategory('All');setState('All')}}>Reset filters</button>}/>}</div></div>;
}
function EmptyState({title,text,action}) { return <div className="empty-state"><div className="empty-symbol">—</div><h2>{title}</h2><p>{text}</p>{action}</div>; }
function Detail({ heritage }) { const {id}=useParams(); const item=heritage.find(x=>x.id===id); const related=heritage.filter(x=>x.id!==id && (x.state===item?.state||x.category===item?.category)).slice(0,3); if(!item) return <div className="container page"><EmptyState title="Heritage entry not found" text="The link may be outdated or the entry has not been added to the MVP dataset." action={<Link className="btn primary" to="/explore">Back to explorer</Link>}/></div>; return <div className="detail-page"><div className="container detail-hero"><div className="detail-image"><Image src={item.image} alt={item.name}/><div className="image-credit">Image source: Wikimedia Commons</div></div><div className="detail-intro"><p className="eyebrow">{item.category} · {item.state}</p><h1>{item.name}</h1><p className="location">{item.city}, {item.state}</p><p>{item.description}</p><div className="detail-actions"><Link className="btn primary" to={`/map?focus=${item.id}`}>View on Map</Link><Link className="btn secondary" to={`/ai?q=${encodeURIComponent(`Tell me about ${item.name}`)}`}>Ask Virasat AI</Link></div></div></div><div className="container detail-content"><article><p className="eyebrow">The story</p><h2>Overview</h2><p>{item.history}</p><h2>Cultural significance</h2><p>{item.significance}</p></article><aside><div className="facts"><p className="eyebrow">Good to know</p><ul>{item.facts.map(f=><li key={f}>{f}</li>)}</ul></div><div className="tags">{item.tags.slice(0,5).map(t=><span key={t}>#{t}</span>)}</div></aside></div>{related.length>0&&<section className="container related"><SectionIntro eyebrow="Continue the trail" title="Related heritage"/><div className="related-grid">{related.map(x=><HeritageCard key={x.id} item={x} compact/>)}</div></section>}</div>; }
function MapFocus({ id }) { const map=useMap(); useEffect(()=>{ if(id) map.setView([id.latitude,id.longitude], 10); },[id,map]); return null; }
function MapPage({ heritage }) { const params=new URLSearchParams(useLocation().search); const focus=heritage.find(x=>x.id===params.get('focus')); const [category,setCategory]=useState('All'); const [state,setState]=useState('All'); const states=[...new Set(heritage.map(x=>x.state))].sort(); const items=heritage.filter(x=>(category==='All'||x.category===category)&&(state==='All'||x.state===state)); const icon=new L.DivIcon({className:'heritage-marker',html:'<span></span>',iconSize:[18,18],iconAnchor:[9,9]}); return <div className="map-page"><div className="container map-head"><div><p className="eyebrow">Interactive map</p><h1>Heritage, placed in context.</h1><p>Explore the locations in our MVP dataset and open a marker for a quick story.</p></div><div className="map-controls"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={state} onChange={e=>setState(e.target.value)}><option>All</option>{states.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="map-shell"><MapContainer center={[22.5,79]} zoom={5} scrollWheelZoom={true} className="leaflet-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{focus&&<MapFocus id={focus}/>} {items.map(item=><Marker key={item.id} position={[item.latitude,item.longitude]} icon={icon}><Popup><div className="map-popup"><Image src={item.image} alt=""/><p className="eyebrow">{item.category}</p><h3>{item.name}</h3><p>{item.city}, {item.state}</p><Link to={`/heritage/${item.id}`}>Read the story →</Link></div></Popup></Marker>)}</MapContainer></div><div className="container map-list"><p className="eyebrow">Visible entries</p><div>{items.map(item=><Link key={item.id} to={`/heritage/${item.id}`}><span>{item.name}</span><span>{item.state}</span><span>→</span></Link>)}</div></div></div>; }
function AIPage() { const [messages,setMessages]=useState([{role:'assistant',text:'Namaste. I’m Virasat AI — the heritage guide inside this MVP. Ask me about a place, tradition, craft or region.'}]); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const suggested=['What is the history of Sanchi Stupa?','Why is Madhubani painting important?','Tell me about traditional architecture in Rajasthan.','Which heritage places can I visit in Madhya Pradesh?']; const location=useLocation(); useEffect(()=>{ const q=new URLSearchParams(location.search).get('q'); if(q){setInput(q)} },[location.search]); async function send(text=input){ if(!text.trim()||loading)return; const question=text.trim(); setInput(''); setMessages(m=>[...m,{role:'user',text:question}]); setLoading(true); const result=await askVirasat(question); setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',text:result.answer,mode:result.mode}]);setLoading(false)},450); }
  return <div className="page ai-page"><div className="container ai-layout"><div className="ai-heading"><p className="eyebrow">Virasat AI</p><h1>A heritage guide, built for the curious.</h1><p>Ask naturally. For the SIH MVP, answers are generated from a local demo knowledge base — not a hidden or simulated external AI call.</p></div><div className="chat-panel"><div className="chat-top"><span>Virasat AI · Demo Knowledge</span><button onClick={()=>setMessages([messages[0]])}>Clear chat</button></div><div className="chat-body">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}><div>{m.text}</div>{m.mode&&<small>Source: local MVP heritage dataset</small>}</div>)}{loading&&<div className="message assistant"><div className="thinking"><i/><i/><i/></div></div>}</div><div className="suggestions">{suggested.map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about India's heritage..." aria-label="Ask Virasat AI"/><button className="btn dark" type="submit">Ask <span>↗</span></button></form></div></div></div>;
}
const quizQuestions=[
 {q:'Which UNESCO World Heritage Site is located in Madhya Pradesh?',options:['Sanchi','Konark','Ajanta','Kaziranga'],answer:'Sanchi',explain:'Sanchi, near Bhopal, is a UNESCO World Heritage Site known for its Buddhist monuments.'},
 {q:'Madhubani painting is associated with which region?',options:['Mithila','Malwa','Konkan','Doab'],answer:'Mithila',explain:'Madhubani painting developed in the Mithila region of Bihar.'},
 {q:'The Sun Temple at Konark was built under which dynasty?',options:['Chola','Eastern Ganga','Chandela','Maurya'],answer:'Eastern Ganga',explain:'The 13th-century temple was built during the reign of Narasimhadeva I of the Eastern Ganga dynasty.'},
 {q:'Channapatna is especially known for which craft?',options:['Wooden toys','Stone inlay','Metal casting','Textile weaving'],answer:'Wooden toys',explain:'Channapatna in Karnataka is renowned for lacquer-finished wooden toys and craftwork.'},
 {q:'Where is the Hornbill Festival held?',options:['Kisama, Nagaland','Kochi, Kerala','Mysuru, Karnataka','Jaisalmer, Rajasthan'],answer:'Kisama, Nagaland',explain:'The festival takes place at Kisama Heritage Village near Kohima.'}
];
function Quiz(){ const [index,setIndex]=useState(0); const [score,setScore]=useState(0); const [selected,setSelected]=useState(null); const [done,setDone]=useState(false); const current=quizQuestions[index]; function choose(option){ if(selected)return; setSelected(option); if(option===current.answer)setScore(s=>s+1); } function next(){ if(index===quizQuestions.length-1)setDone(true); else {setIndex(i=>i+1);setSelected(null);} } function restart(){setIndex(0);setScore(0);setSelected(null);setDone(false)} return <div className="page quiz-page"><div className="container quiz-wrap"><div className="quiz-intro"><p className="eyebrow">Heritage quiz</p><h1>How well do you know the stories?</h1><p>A quick five-question trail through places, art and living traditions.</p></div>{done?<div className="quiz-result"><span className="result-number">{score}<small>/ {quizQuestions.length}</small></span><p className="eyebrow">Your score</p><h2>{score>=4?'You know your heritage.':'Curiosity is a good place to start.'}</h2><p>{score===5?'Perfect trail.':`You got ${score} out of ${quizQuestions.length}. Explore the site and try again.`}</p><button className="btn primary" onClick={restart}>Take it again</button></div>:<div className="quiz-card"><div className="quiz-progress"><span>0{index+1}</span><div><div style={{width:`${((index+1)/quizQuestions.length)*100}%`}}/></div><span>0{quizQuestions.length}</span></div><p className="eyebrow">Question {index+1}</p><h2>{current.q}</h2><div className="options">{current.options.map(o=><button key={o} className={selected ? (o===current.answer?'correct':o===selected?'wrong':'') : ''} onClick={()=>choose(o)} disabled={!!selected}>{o}<span>{selected&&o===current.answer?'✓':selected&&o===selected?'×':''}</span></button>)}</div>{selected&&<div className="quiz-feedback"><strong>{selected===current.answer?'Correct.':'Not quite.'}</strong><span>{current.explain}</span></div>}<div className="quiz-next">{selected&&<button className="btn dark" onClick={next}>{index===quizQuestions.length-1?'See result':'Next question'} →</button>}</div></div>}</div></div> }
function About(){ return <div className="page about-page"><div className="container about-hero"><p className="eyebrow">About Virasat Setu</p><h1>A digital bridge between curious people and India's heritage.</h1><p className="lead">We built Virasat Setu as a student innovation project around one simple observation: good heritage information should be easier to discover, understand and connect.</p></div><div className="container about-grid"><section><p className="eyebrow">The problem</p><h2>Heritage knowledge is rich. Discovery is fragmented.</h2><p>Students often encounter heritage through isolated textbook chapters, travel pages, museum websites, videos or social posts. Virasat Setu experiments with a single, visual entry point that connects stories, places and questions.</p></section><section><p className="eyebrow">Our approach</p><h2>Search → story → map → conversation.</h2><p>The MVP keeps the architecture simple: reusable React components, a structured heritage dataset, an interactive Leaflet map, a local demo knowledge system and a quiz layer for active learning.</p></section></div><div className="container tech-section"><p className="eyebrow">Technology</p><div className="tech-list"><span>React</span><span>Vite</span><span>JavaScript</span><span>Node.js</span><span>Express</span><span>Leaflet</span><span>CSS</span></div></div><div className="container limitations"><div><p className="eyebrow">MVP boundaries</p><h2>Built to demonstrate the idea, not overclaim it.</h2></div><ul><li>The current dataset is intentionally small and curated for demonstration.</li><li>Virasat AI uses local demo responses when an external AI provider is not configured.</li><li>Production expansion would add verified source metadata, multilingual content, moderation, richer mapping and a persistent database.</li></ul></div><div className="container sih-banner"><span>Built as an SIH Student Innovation Project</span><span>Virasat Setu · A bridge to India's living heritage.</span></div></div> }
function App(){ const [heritage,setHeritage]=useState([]); const [loading,setLoading]=useState(true); useEffect(()=>{getHeritage().then(setHeritage).finally(()=>setLoading(false))},[]); if(loading)return <><Header/><div className="app-loading"><div className="loading-mark">VS</div><p>Opening the heritage trail…</p></div></>; return <Layout><Routes><Route path="/" element={<Home heritage={heritage}/>}/><Route path="/explore" element={<Explore heritage={heritage}/>}/><Route path="/heritage/:id" element={<Detail heritage={heritage}/>}/><Route path="/map" element={<MapPage heritage={heritage}/>}/><Route path="/ai" element={<AIPage/>}/><Route path="/quiz" element={<Quiz/>}/><Route path="/about" element={<About/>}/><Route path="*" element={<NotFound/>}/></Routes></Layout>; }
function NotFound(){return <div className="container page"><EmptyState title="This trail ends here." text="The page you requested does not exist." action={<Link className="btn primary" to="/">Return home</Link>}/></div>}
export default App;
